'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
i, one, two, fib_sum = 0, 0, 1, 0

while True:
	if i <= 1:
		next_num = i
	else:
		next_num = one + two
		one = two
		two = next_num
		if two < 4000000:
			if two % 2 == 0:
				fib_sum += two
		else:
			break
	i += 1

print(str(fib_sum))